#!/usr/bin/env python

import json
import os
import sys
from os.path import expanduser

f = open(expanduser('~/.dropbox/info.json'), 'r')
info = json.loads(f.read())

pth = os.path.abspath((len(sys.argv) > 1 and sys.argv[1]) or os.getcwd())
pth = os.path.realpath(pth)

dropboxPath = info["personal"]["path"]

if not dropboxPath in pth:
    print("That's not a Dropbox path")
    sys.exit(1)

strippedPath = pth.replace(dropboxPath, "")

os.system('open "https://www.dropbox.com/home%s"' % strippedPath)
